hapi:
  fhir:
    # Enable validation
    validation:
      enabled: true
    # Set the server to allow for easier development and testing
    narrative:
      serverBaseUrl: "http://localhost:9090/fhir"
    # Allow cross-origin requests for development
    cors:
      allow_credentials: true
      allowed_origin:
        - "*"

# Spring configuration for database connection
spring:
  datasource:
    url: 'jdbc:postgresql://postgres:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false
      # Disable Lucene-based search for now, can be enabled with proper configuration
      hibernate.search.backend.type: lucene
      hibernate.search.backend.directory.type: local-filesystem
      hibernate.search.backend.directory.root: target/lucenefiles
      hibernate.search.backend.lucene_version: lucene_current 