version: '3.8'

services:
  # HAPI FHIR server
  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir-jpaserver
    ports:
      - "9090:8080"
    environment:
      - spring.config.import=optional:file:/app/config/application.yaml
      - hapi.fhir.validation.enabled=true
      - hapi.fhir.narrative.serverBaseUrl=http://localhost:9090/fhir
      # Note: implementationguides config is handled in application.yaml
      - "hapi.fhir.cors.allow_credentials=true"
      - "hapi.fhir.cors.allowed_origin=*"
      - hapi.fhir.allow_multiple_delete=true
      - hapi.fhir.allow_external_references=true
    volumes:
      - ./application.yaml:/app/config/application.yaml:ro
      - hapi-data:/data/hapi
    restart: unless-stopped
    networks:
      - medicare-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/fhir/metadata" ]
      interval: 30s
      timeout: 10s
      retries: 5

  # MongoDB for our NestJS application
  mongodb:
    image: mongo:latest
    container_name: medicare-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    networks:
      - medicare-network
    environment:
      MONGO_INITDB_DATABASE: medicare

volumes:
  hapi-data:
  mongodb-data:


networks:
  medicare-network:
    driver: bridge
