name: medicare-fhir-platform
region: nyc
services:
  - name: nest-backend
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/fhir-ehr-platform
    build_command: npm install && npm run build
    run_command: npm run start:prod
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: API_PREFIX
        value: api
      - key: API_VERSION
        value: v1
      - key: CORS_ENABLED
        value: "true"
      - key: MONGODB_URI
        value: ${mongodb.DATABASE_URL}
      - key: JWT_SECRET
        value: ${jwt.SECRET}
        type: SECRET
      - key: JWT_EXPIRATION
        value: 1d
      - key: FHIR_SERVER_URL
        value: ${hapi-fhir.PRIVATE_URL}/fhir
      - key: FHIR_MODE
        value: hybrid
      - key: FHIR_VERSION
        value: R4
      - key: FHIR_AUTH_TYPE
        value: none
      - key: LOCAL_FHIR_RESOURCES
        value: Patient,Practitioner,Organization,Encounter,Observation,DiagnosticReport,Medication,Questionnaire,Payment
      - key: LOG_LEVEL
        value: info
      - key: EMAIL_SERVICE
        value: ${email.SERVICE}
      - key: EMAIL_HOST
        value: ${email.HOST}
      - key: EMAIL_PORT
        value: ${email.PORT}
      - key: EMAIL_USER
        value: ${email.USER}
      - key: EMAIL_PASSWORD
        value: ${email.PASSWORD}
        type: SECRET
      - key: EMAIL_FROM
        value: ${email.FROM}
      - key: ACCESS_CODE_EXPIRES_IN
        value: 7d
      - key: RESET_CODE_EXPIRES_IN
        value: 1h
      - key: API_DOCS_PATH
        value: api-docs
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    health_check:
      http_path: /api/health

  - name: hapi-fhir
    image:
      registry_type: DOCKER_HUB
      registry: hapiproject
      repository: hapi
      tag: latest
    envs:
      - key: spring.config.import
        value: optional:file:/app/config/application.yaml
      - key: hapi.fhir.validation.enabled
        value: "true"
      - key: hapi.fhir.narrative.serverBaseUrl
        value: ${_self.PUBLIC_URL}/fhir
      - key: hapi.fhir.cors.allow_credentials
        value: "true"
      - key: hapi.fhir.cors.allowed_origin
        value: "*"
      - key: hapi.fhir.allow_multiple_delete
        value: "true"
      - key: hapi.fhir.allow_external_references
        value: "true"
    http_port: 8080
    volumes:
      - volume_name: hapi-data
        mount_path: /data/hapi
    routes:
      - path: /fhir
        preserve_path_prefix: true
    health_check:
      http_path: /fhir/metadata
    instance_count: 1
    instance_size_slug: basic-xs

databases:
  - name: mongodb
    engine: MONGODB
    version: 6.0
    production: true
    db_name: medicare
    cluster_name: medicare-mongodb
    cluster_size: db-s-1vcpu-1gb

volumes:
  - name: hapi-data
    mount_path: /data/hapi
    size_gb: 5

secrets:
  - key: jwt.SECRET
    type: SECRET
    value: "your-secure-jwt-secret-for-production"
  - key: email.SERVICE
    value: "gmail"
  - key: email.HOST
    value: "smtp.gmail.com"
  - key: email.PORT
    value: "587"
  - key: email.USER
    value: "your-email@example.com"
  - key: email.PASSWORD
    type: SECRET
    value: "your-email-password"
  - key: email.FROM
    value: "Your App Name <your-email@example.com>" 