global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'medicare-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['nest-api:3000']

  - job_name: 'hapi-fhir'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['hapi-fhir:8080']